### PR TITLE
support python 3.12

### PR DESCRIPTION
**Pull request by jsiverskog**

### CODE REVIEW

**Comment by eerimoq** [comment]
Looks like setuptools is needed on Appveyor in 3.12.

**Comment by eerimoq** [comment]
Other than that I think it looks good.

**Comment by jsiverskog** [comment]
> Looks like setuptools is needed on Appveyor in 3.12.

ah, i added it to appveyor as well now.

**Comment by eerimoq** [comment]
strange. one job still fails

**Comment by jsiverskog** [comment]
> strange. one job still fails

now fixed (pip was called incorrectly)!

**Comment by jsiverskog** [comment]
tack!

do you mind pushing a new release to pypi? thanks.

**Comment by eerimoq** [comment]
0.13.0

**Pull request merged**
